### ISSUE TITLE
OpenArtBrowser Search Query - BodyBuilder JS

### ISSUE THREAD

**Issue by vinoroidski** [hochschule-darmstadt/openartbrowser-social#1]
Goal: write a query which can retrieve a random artwork each time it is called. None of the following keywords should appear in its data:

areola
breast
butt
erotic
intercourse
masturbate
nipple
nude
nudity
orgy
penis
sex
sensual
vagina
voyeur

**Comment by BernhardHumm** [comment]
For the social media bot:

It is not a good idea to pick a random artwork independent of the rank.

Better idea: simply use the top-ranked entities (artworks, artists, genres, movements, locations, etc.) and make sure that you never repeat one and that you change the entity type each week. So you get interesting entities and have a good mixture and the implementation is simple.

 

(BTW Michelangelo’s David is certainly interesting although he is naked)

 

 

 

Von: vinoroidski ***@***.***> 
Gesendet: Donnerstag, 22. April 2021 22:12
An: hochschule-darmstadt/openartbrowser-social ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [hochschule-darmstadt/openartbrowser-social] OpenArtBrowser Search Query - BodyBuilder JS (#1)

 

Goal: write a query which can retrieve a random artwork each time it is called. None of the following keywords should appear in its data:

breast
butt
erotic
intercourse
masturbate
nipple
nude
nudity
orgy
penis
sex
sensual
vagina
voyeur

**Comment by vinoroidski** [comment]
- use the top-ranked entities (artworks only in MVP) 
- never repeat one

Completed.
