### ISSUE TITLE
Method for image download

### ISSUE THREAD

**Issue by vinoroidski** [hochschule-darmstadt/openartbrowser-social#9]
Write a method to download any image we require for the tweet post.
@ahmadf0311 : please add details and close post.

**Comment by ahmadf0311** [comment]
The method image_download(link, filename) is defined for downloading a photo to save the photo according to a link in the desired filename(home directory in staging). 
link is actually the Address of the photo which returns from the Elasticsearch based on the given postQIDPos(index of postQID in list of all artworkQIDs).
image_name is also the name of the photo, which is saved with the PNG extension and the name of the postQID.
